Algoritmo "Área e perímetro de um retangulo"
// Disciplina : PA
// Professor : Edilma Bindá
// Aluno : Lucas Martins Pereira
// Data atual : 23/02/2023
// Turma : 1 C Turma B
Var
area, base, altura: real


//entrada
inicio
escreval ("Digite a base do retângulo: ")
leia (base)
escreval ("Digite a altura do retângulo: ")
leia (altura)

//processamento
area <- base * altura

//saída
escreval ("A área do retângulo é: ", area)

fimalgoritmo