Algoritmo "consumo de combustÌvel"
// Disciplina : PA
// Professor : Edilma Bindá
// Aluno : Lucas Martins Pereira
// Data atual : 02/03/2023
// Turma : 1 C Turma B
Var
media, km, combustivel:real

//entrada
inicio
escreval ("Determine a distância percorrida: ")
leia (km)
escreval ("Determine o total de combustível gasto: ")
leia (combustivel)

//processamento
media <- km/combustivel

//saída
escreval ("O consumo médio do automóvel é: ", media)

fimalgoritmo