Algoritmo "Média do bimestre"
// Disciplina : PA
// Professor : Edilma Bindá
// Aluno : Lucas Martins Pereira
// Data atual : 02/03/2023
// Turma : 1 C Turma B
Var
total, media:real
nome:caractere

//entrada
inicio
escreval ("Escreva seu nome: ")
leia (nome)
escreval ("Some suas três últimas notas e insira: ")
leia (total)

//processamento
media <- total/3

//saída
escreval ("A sua média do bimestre, ", nome, ", é: ", media)

fimalgoritmo