Algoritmo "conversão de Celsius em Fahrenheit "
// Disciplina : PA
// Professor : Edilma Bindá
// Aluno : Lucas Martins Pereira
// Data atual : 09/03/2023
// Turma : 1 C Turma B
Var
celsius, fahrenheit:real
Inicio
escreval ("Informe a temperatura em graus Celsius")
leia (celsius)

//processamento
fahrenheit <-  (9*celsius+160)/5

//saída
escreval ("A medida da temperatura em graus Fahrenheit é de", fahrenheit)

Fimalgoritmo