Algoritmo "Temperatura"
// Disciplina : PA
// Professor  : Edilma Bindá
// Turma      : 1 C TURMA B
// Autor      : Lucas Martins Pereira
// Data       : 02/06/2023
Var
num: real

//ENTRADA
inicio
escreval ("Escreva um número")
leia (num)

//PROCESSAMENTO E SAÍDA
se ((num>=100) e (num<=200))entao
escreval ("Esse número está entre 100 e 200!")
senao
escreval ("Esse número está fora do intervalo entre 100 e 200!")
fimse

fimalgoritmo

