Algoritmo "Positivo e negativo"
// Disciplina  :PA
// Professor   :Edilma Bindá
// Turma       :1 C TURMA B
// Autor(a)    :Lucas Martins Pereira
// Data atual  : 25/05/2023
Var
salario, gasto:real

//ENTRADA
inicio
escreval ("Informe o seu salário")
leia (salario)
escreval ("Informe o seu gasto mensal")
leia (gasto)

//PROCESSAMENTO E SAÍDA
se salario <= gasto entao
escreval ("O seu saldo será negativo")
senao
escreval ("O seu saldo será positivo")
fimse

fimalgoritmo