Algoritmo "semnome"
// Disciplina  :PA
// Professor   :Edilma Bindá
// Turma       :1 C TURMA B
// Autor(a)    :Lucas Martins Pereira
// Data atual  : 25/05/2023
Var
idade:real

//ENTRADA
inicio
escreval ("Começou!")
escreval ("Informe a sua idade")
leia (idade)

//PROCESSAMENTO E SAÍDA
se idade >= 18 entao
escreval ("Ok, pode passar")
senao
escreval ("Você não  pode dirigir")
fimse

escreval ("Acabou!")

fimalgoritmo