Algoritmo "Maior ou menor de idade"
// Disciplina  :PA
// Professor   :Edilma Bindá
// Turma       :1 C TURMA B
// Autor(a)    :Lucas Martins Pereira
// Data atual  : 25/05/2023
Var
idade :real
nome :caractere

//ENTRADA
inicio
escreval ("Escreva o seu nome")
leia(nome)
escreval ("Escreva a sua idade")
leia(idade)

//PROCESSAMENTO E SAÍDA
se idade >= 18 entao
escreval (nome, ", você é maior de idade")
senao
escreval (nome, ", você é menor de idade")
fimse

fimalgoritmo