Algoritmo "Número maior que 10"
// Disciplina  :PA
// Professor   :Edilma Bindá
// Turma       :1 C TURMA B
// Autor(a)    :Lucas Martins Pereira
// Data atual  : 25/05/2023
Var
numero:real

//ENTRADA
inicio
escreval ("Apresente um número")
leia (numero)

//PROCESSAMENTO E SAÍDA
se numero >= 10 entao
escreval ("Este número é maior do que 10")
senao
escreval ("Este número é menor do que 10")
fimse

fimalgoritmo